function createQuizRepository(sql,setupRoles){
 let ready;
 function setup(){if(!ready)ready=setupRoles().then(()=>sql.transaction([
  sql.query(`CREATE TABLE IF NOT EXISTS concept_quiz_editors(google_id TEXT NOT NULL REFERENCES teaching_assistants(google_id) ON DELETE CASCADE,course VARCHAR(100) NOT NULL,PRIMARY KEY(google_id,course))`),
  sql.query(`CREATE TABLE IF NOT EXISTS concept_quiz_sets(id UUID PRIMARY KEY,course VARCHAR(100) NOT NULL,lesson VARCHAR(150) NOT NULL,sections JSONB,created_by TEXT NOT NULL REFERENCES login_dev_users(google_id),target INTEGER NOT NULL CHECK(target BETWEEN 1 AND 50),state JSONB NOT NULL,version INTEGER NOT NULL DEFAULT 0,published BOOLEAN NOT NULL DEFAULT false,request_id UUID,busy_until TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp())`),
  sql.query(`CREATE TABLE IF NOT EXISTS concept_quiz_questions(id UUID PRIMARY KEY,set_id UUID NOT NULL REFERENCES concept_quiz_sets(id),parent_id UUID REFERENCES concept_quiz_questions(id),content JSONB NOT NULL,context_hash TEXT NOT NULL,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp())`),
  sql.query(`CREATE TABLE IF NOT EXISTS concept_quiz_answers(id UUID PRIMARY KEY,question_id UUID NOT NULL REFERENCES concept_quiz_questions(id),google_id TEXT NOT NULL REFERENCES login_dev_users(google_id) ON DELETE CASCADE,choice INTEGER NOT NULL CHECK(choice BETWEEN 0 AND 3),correct BOOLEAN NOT NULL,understood BOOLEAN NOT NULL DEFAULT false,comment TEXT NOT NULL DEFAULT '' CHECK(length(comment)<=2000),review_status TEXT NOT NULL DEFAULT 'unreviewed' CHECK(review_status IN ('unreviewed','planned','resolved','keep')),review_note TEXT NOT NULL DEFAULT '' CHECK(length(review_note)<=2000),review_version INTEGER NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp())`),
  sql.query(`CREATE TABLE IF NOT EXISTS concept_quiz_usage(google_id TEXT NOT NULL REFERENCES login_dev_users(google_id) ON DELETE CASCADE,day DATE NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,PRIMARY KEY(google_id,day))`),
  sql.query(`CREATE INDEX IF NOT EXISTS concept_quiz_answer_lookup ON concept_quiz_answers(question_id,google_id,created_at,id)`),
  sql.query(`CREATE INDEX IF NOT EXISTS concept_quiz_lesson_lookup ON concept_quiz_sets(course,lesson)`)
 ])).catch(e=>{ready=undefined;throw e;});return ready;}
 const fields=`id::text,course,lesson,sections,target,state,version,published,request_id AS "requestId",busy_until AS "busyUntil"`;
 const visible=`(s.sections IS NULL OR EXISTS(SELECT 1 FROM login_dev_roster r JOIN login_dev_enrollments e ON e.roster_id=r.id WHERE r.google_id=$3 AND e.course_id=$4 AND s.sections ? e.section))`;
 const audience=`EXISTS(SELECT 1 FROM login_dev_roster r JOIN login_dev_enrollments e ON e.roster_id=r.id WHERE r.google_id=a.google_id AND e.course_id=$3 AND ($4::jsonb IS NULL OR $4::jsonb ? e.section))`;
 return {
  setupQuiz:setup,
  async quizCanEdit(user,course){await setup();return (await sql.query('SELECT 1 FROM concept_quiz_editors WHERE google_id=$1 AND course=$2',[user,course])).length>0;},
  async quizEditors(course){await setup();return sql.query(`SELECT r.id::text AS id,r.student_name AS name,(q.google_id IS NOT NULL) AS enabled FROM teaching_assistants t JOIN login_dev_roster r ON r.google_id=t.google_id LEFT JOIN concept_quiz_editors q ON q.google_id=t.google_id AND q.course=$1 ORDER BY r.student_name`,[course]);},
  async quizGrant(studentId,course,enabled){await setup();const rows=await sql.query(`WITH eligible AS(SELECT t.google_id FROM teaching_assistants t JOIN login_dev_roster r ON r.google_id=t.google_id WHERE r.id=$1::bigint),removed AS(DELETE FROM concept_quiz_editors WHERE google_id IN(SELECT google_id FROM eligible) AND course=$2 AND NOT $3 RETURNING google_id),added AS(INSERT INTO concept_quiz_editors SELECT google_id,$2 FROM eligible WHERE $3 ON CONFLICT DO NOTHING RETURNING google_id) SELECT google_id FROM eligible`,[studentId,course,enabled]);return !!rows.length;},
  async quizCreate(id,user,course,lesson,sections,target){await setup();const rows=await sql.query(`INSERT INTO concept_quiz_sets(id,created_by,course,lesson,sections,target,state) VALUES($1::uuid,$2,$3,$4,$5::jsonb,$6,$7::jsonb) RETURNING ${fields}`,[id,user,course,lesson,sections===null?null:JSON.stringify(sections),target,JSON.stringify({messages:[],items:[],proposals:[]})]);return rows[0];},
  async quizSets(course,lesson){await setup();return sql.query(`SELECT ${fields} FROM concept_quiz_sets WHERE course=$1 AND lesson=$2 ORDER BY created_at DESC LIMIT 100`,[course,lesson]);},
  async quizSet(id,course,lesson){await setup();return (await sql.query(`SELECT ${fields} FROM concept_quiz_sets WHERE id=$1::uuid AND course=$2 AND lesson=$3`,[id,course,lesson]))[0]||null;},
  async quizBegin(id,user,version,requestId){await setup();return (await sql.query(`WITH candidate AS(SELECT id FROM concept_quiz_sets WHERE id=$1::uuid AND version=$3 AND (busy_until IS NULL OR busy_until<clock_timestamp()) FOR UPDATE),quota AS(INSERT INTO concept_quiz_usage(google_id,day,attempts) SELECT $2,(clock_timestamp() AT TIME ZONE 'UTC')::date,1 WHERE EXISTS(SELECT 1 FROM candidate) ON CONFLICT(google_id,day) DO UPDATE SET attempts=concept_quiz_usage.attempts+1 WHERE concept_quiz_usage.attempts<60 RETURNING google_id) UPDATE concept_quiz_sets SET request_id=$4::uuid,busy_until=clock_timestamp()+interval '90 seconds' WHERE id=$1::uuid AND EXISTS(SELECT 1 FROM quota) RETURNING ${fields}`,[id,user,version,requestId]))[0]||null;},
  async quizFinish(id,version,requestId,state){return (await sql.query(`UPDATE concept_quiz_sets SET state=$4::jsonb,version=version+1,busy_until=NULL WHERE id=$1::uuid AND version=$2 AND request_id=$3::uuid AND busy_until IS NOT NULL RETURNING ${fields}`,[id,version,requestId,JSON.stringify(state)]))[0]||null;},
  async quizCancel(id,requestId){await sql.query('UPDATE concept_quiz_sets SET busy_until=NULL,request_id=NULL WHERE id=$1::uuid AND request_id=$2::uuid',[id,requestId]);},
  async quizApply(id,version,change){await setup();return (await sql.query(`WITH saved AS(UPDATE concept_quiz_sets SET state=$3::jsonb,version=version+1,published=published OR $6,request_id=NULL,target=$7 WHERE id=$1::uuid AND version=$2 AND (busy_until IS NULL OR busy_until<clock_timestamp()) RETURNING *),retired AS(UPDATE concept_quiz_questions SET active=false WHERE set_id=$1::uuid AND id IN(SELECT value::uuid FROM jsonb_array_elements_text($5::jsonb)) AND EXISTS(SELECT 1 FROM saved) RETURNING id),added AS(INSERT INTO concept_quiz_questions(id,set_id,parent_id,content,context_hash) SELECT (p->>'id')::uuid,$1::uuid,(p->>'replaces')::uuid,p,p->>'contextHash' FROM jsonb_array_elements($4::jsonb) p WHERE EXISTS(SELECT 1 FROM saved) ON CONFLICT(id) DO NOTHING RETURNING id) SELECT ${fields} FROM saved`,[id,version,JSON.stringify(change.state),JSON.stringify(change.publications),JSON.stringify(change.retired),!!change.publications.length,change.target]))[0]||null;},
  async quizStudentQuestions(course,lesson,user,code){await setup();return sql.query(`SELECT q.id::text,q.content,q.context_hash AS "contextHash",EXISTS(SELECT 1 FROM concept_quiz_answers a WHERE a.question_id=q.id AND a.google_id=$3) AS answered FROM concept_quiz_questions q JOIN concept_quiz_sets s ON s.id=q.set_id WHERE s.course=$1 AND s.lesson=$2 AND q.active AND ${visible} ORDER BY q.created_at,q.id LIMIT 300`,[course,lesson,user,code]);},
  async quizAnswer(course,lesson,user,code,questionId,choice,requestId){await setup();const rows=await sql.query(`INSERT INTO concept_quiz_answers(id,question_id,google_id,choice,correct) SELECT $7::uuid,q.id,$3,$6,($6=(q.content->>'answer')::int) FROM concept_quiz_questions q JOIN concept_quiz_sets s ON s.id=q.set_id WHERE s.course=$1 AND s.lesson=$2 AND q.id=$5::uuid AND q.active AND ${visible} ON CONFLICT(id) DO NOTHING RETURNING id::text`,[course,lesson,user,code,questionId,choice,requestId]);return rows.length?this.quizAnswerDetail(course,lesson,user,requestId):this.quizAnswerDetail(course,lesson,user,requestId,questionId,choice);},
  async quizAnswerDetail(course,lesson,user,id,questionId=null,choice=null){await setup();return (await sql.query(`SELECT a.id::text,a.question_id::text AS "questionId",a.choice,a.correct,a.understood,a.comment,q.content FROM concept_quiz_answers a JOIN concept_quiz_questions q ON q.id=a.question_id JOIN concept_quiz_sets s ON s.id=q.set_id WHERE s.course=$1 AND s.lesson=$2 AND a.google_id=$3 AND a.id=$4::uuid AND ($5::uuid IS NULL OR a.question_id=$5::uuid) AND ($6::int IS NULL OR a.choice=$6)`,[course,lesson,user,id,questionId,choice]))[0]||null;},
  async quizOwnAnswers(course,lesson,user){await setup();return sql.query(`SELECT DISTINCT ON(a.question_id) a.id::text,a.question_id::text AS "questionId",a.choice,a.correct,a.understood,a.comment,q.content FROM concept_quiz_answers a JOIN concept_quiz_questions q ON q.id=a.question_id JOIN concept_quiz_sets s ON s.id=q.set_id WHERE s.course=$1 AND s.lesson=$2 AND a.google_id=$3 ORDER BY a.question_id,a.created_at DESC,a.id DESC LIMIT 300`,[course,lesson,user]);},
  async quizFeedback(course,lesson,user,id,understood,comment){await setup();return (await sql.query(`UPDATE concept_quiz_answers a SET understood=$5,comment=$6,review_status=CASE WHEN comment IS DISTINCT FROM $6 THEN 'unreviewed' ELSE review_status END,review_version=review_version+1 FROM concept_quiz_questions q JOIN concept_quiz_sets s ON s.id=q.set_id WHERE a.question_id=q.id AND s.course=$1 AND s.lesson=$2 AND a.google_id=$3 AND a.id=$4::uuid RETURNING a.id::text`,[course,lesson,user,id,understood,comment]))[0]||null;},
  async quizStats(course,lesson,code,sections){await setup();const args=[course,lesson,code,sections===null?null:JSON.stringify(sections)];
   const questions=await sql.query(`WITH ranked AS(SELECT a.*,row_number() OVER(PARTITION BY a.question_id,a.google_id ORDER BY a.created_at,a.id) AS attempt FROM concept_quiz_answers a WHERE ${audience}) SELECT q.id::text,q.parent_id::text AS "parentId",q.content,q.context_hash AS "contextHash",q.active,count(a.id)::int AS attempts,count(a.id) FILTER(WHERE a.attempt=1)::int AS participants,count(a.id) FILTER(WHERE a.attempt=1 AND a.correct)::int AS correct,count(a.id) FILTER(WHERE a.understood AND NOT a.correct)::int AS understood,count(a.id) FILTER(WHERE a.comment<>'')::int AS comments,count(a.id) FILTER(WHERE a.comment<>'' AND a.review_status IN ('unreviewed','planned'))::int AS "openComments",ARRAY[count(a.id) FILTER(WHERE a.attempt=1 AND a.choice=0),count(a.id) FILTER(WHERE a.attempt=1 AND a.choice=1),count(a.id) FILTER(WHERE a.attempt=1 AND a.choice=2),count(a.id) FILTER(WHERE a.attempt=1 AND a.choice=3)] AS choices FROM concept_quiz_questions q JOIN concept_quiz_sets s ON s.id=q.set_id LEFT JOIN ranked a ON a.question_id=q.id WHERE s.course=$1 AND s.lesson=$2 GROUP BY q.id ORDER BY q.created_at DESC LIMIT 500`,args);
   const answers=await sql.query(`SELECT a.id::text,a.question_id::text AS "questionId",a.choice,a.correct,a.understood,a.comment,a.review_status AS "reviewStatus",a.review_note AS "reviewNote",a.review_version AS "reviewVersion",r.student_name AS name,r.student_number AS "studentNumber",a.created_at AS "createdAt" FROM concept_quiz_answers a JOIN concept_quiz_questions q ON q.id=a.question_id JOIN concept_quiz_sets s ON s.id=q.set_id JOIN login_dev_roster r ON r.google_id=a.google_id WHERE s.course=$1 AND s.lesson=$2 AND ${audience} ORDER BY a.created_at DESC LIMIT 500`,args);
   const eligible=await sql.query(`SELECT count(*)::int AS total FROM login_dev_roster r WHERE r.google_id IS NOT NULL AND EXISTS(SELECT 1 FROM login_dev_enrollments e WHERE e.roster_id=r.id AND e.course_id=$1 AND ($2::jsonb IS NULL OR $2::jsonb ? e.section))`,[code,sections===null?null:JSON.stringify(sections)]);
   return {questions,answers,eligible:eligible[0].total,limit:500};
  },
  async quizReview(course,lesson,code,sections,id,status,note,version){await setup();return (await sql.query(`UPDATE concept_quiz_answers a SET review_status=$6,review_note=$7,review_version=review_version+1 FROM concept_quiz_questions q JOIN concept_quiz_sets s ON s.id=q.set_id WHERE a.question_id=q.id AND s.course=$1 AND s.lesson=$2 AND ${audience} AND a.id=$5::uuid AND a.review_version=$8 AND a.comment<>'' RETURNING a.id::text`,[course,lesson,code,sections===null?null:JSON.stringify(sections),id,status,note,version]))[0]||null;}
 };
}
module.exports={createQuizRepository};
