const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..'),out=path.join(root,'public');
const marker=path.join(out,'.generated-site');
if(fs.existsSync(out)) {
 if(fs.lstatSync(out).isSymbolicLink() || fs.realpathSync(out)!==out || !fs.existsSync(marker)) throw new Error('Refusing to replace an unmarked public directory.');
 fs.rmSync(out,{recursive:true});
}
fs.mkdirSync(out);
fs.writeFileSync(marker,'Generated by scripts/build-public.js');
const allowedExt=new Set(['.html','.css','.js','.png','.jpg','.jpeg','.webp','.gif','.svg','.ico','.pdf','.woff','.woff2','.ttf','.csv']);
function copy(source,destination) {
 const stat=fs.lstatSync(source);
 if(stat.isSymbolicLink()) throw new Error('Symlinks are not published.');
 if(stat.isDirectory()) {
  fs.mkdirSync(destination,{recursive:true});
  for(const name of fs.readdirSync(source)) if(!name.startsWith('.')) copy(path.join(source,name),path.join(destination,name));
 } else if(allowedExt.has(path.extname(source).toLowerCase())) fs.copyFileSync(source,destination);
}
for(const name of ['index.html','assets','materials','2026-2-python_adv','2026-2-java_basic']) copy(path.join(root,name),path.join(out,name));
copy(path.join(root,'auth-dev/public'),path.join(out,'auth-assets'));
// Only login shell is public at its top-level URL. courses/admin URLs retain server guards.
copy(path.join(root,'auth-dev/public/login.html'),path.join(out,'login.html'));
const index=path.join(out,'index.html');
fs.writeFileSync(index,fs.readFileSync(index,'utf8').replace('</header>','<div class="wrap"><p><a style="color:inherit" href="/login.html">로그인 · 내 강의자료</a></p></div></header>'));
console.log('Public lecture materials and login assets built. Server code and environment files excluded.');

for(const folder of ['2026-2-java_basic','2026-2-python_adv']) {
 const file=path.join(out,folder,'index.html');
 if(!fs.readFileSync(file,'utf8').includes('<h1>')) throw new Error('Missing course index: '+folder);
 console.log('Verified static output: '+folder+'/index.html');
}
